// Liste des principales villes du Maroc
export const VILLES_MAROC = [
  "Agadir",
  "Al Hoceima",
  "Asilah",
  "Azrou",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Beni Mellal",
  "Boujad",
  "Boulemane",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "El Kelaa des Sraghna",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Figuig",
  "Guelmim",
  "Ifrane",
  "Kénitra",
  "Khémisset",
  "Khenifra",
  "Khouribga",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Meknès",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Ouazzane",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Settat",
  "Sidi Kacem",
  "Sidi Slimane",
  "Tanger",
  "Tan-Tan",
  "Taounate",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
  "Tiznit",
  "Youssoufia"
];

// Export par défaut et nommé pour compatibilité
export const villesMaroc = VILLES_MAROC;
export default VILLES_MAROC;
