// Liste complète des villes du Maroc pour lieu de naissance
export const villesMarocNaissance = [
  // Grandes villes
  'Casablanca',
  'Rabat',
  'Fès',
  'Marrakech',
  'Agadir',
  'Tangier',
  'Meknès',
  'Oujda',
  'Kenitra',
  'Tétouan',
  
  // Villes moyennes
  'Safi',
  'Mohammedia',
  'Khouribga',
  'Beni Mellal',
  'El Jadida',
  'Nador',
  'Taza',
  'Settat',
  'Larache',
  'Khemisset',
  'Guelmim',
  'Berrechid',
  'Khenifra',
  'Taourirt',
  'Berkane',
  'Skhirate',
  'Jerada',
  'Kasba Tadla',
  'Azrou',
  'Youssoufia',
  'Ouarzazate',
  'Tiznit',
  'Taroudant',
  'Ouezzane',
  'Fnideq',
  'Azemmour',
  'Moulay Idriss Zerhoun',
  'Chefchaouen',
  'Al Hoceima',
  'Midelt',
  'Ifrane',
  'Errachidia',
  'Essaouira',
  'Sidi Bennour',
  'Sidi Slimane',
  'Salé',
  'Temara',
  'Skhirate',
  'Khemisset',
  'Rommani',
  'Ain Harrouda',
  'Bouknadel',
  'Harhoura',
  'Souissi',
  'Bouznika',
  'Ben Slimane',
  'Deroua',
  'Oulad Ayad',
  'Oulad M\'Rah',
  'Oulad Saleh',
  'Sidi Rahhal',
  'Lalla Mimouna',
  'M\'Diq',
  'Martil',
  'Asilah',
  'Ksar el-Kebir',
  'Souk el Arba du Gharb',
  'Sidi Kacem',
  'Mechra Bel Ksiri',
  'Ouazzane',
  'Chefchaouen',
  'Issaguen',
  'Bab Taza',
  'Stehat',
  'Al Hoceima',
  'Imzouren',
  'Bni Bouayach',
  'Ajdir',
  'Targuist',
  'Jebha',
  'Taza',
  'Tahla',
  'Aknoul',
  'Taineste',
  'Oued Amlil',
  'Ghafsai',
  'Matmata',
  'Boulemane',
  'Missour',
  'Outat El Haj',
  'Imouzzer Marmoucha',
  'Ribat El Kheir',
  'Sefrou',
  'Imouzzer Kandar',
  'Bhalil',
  'Moulay Yacoub',
  'Ain Taoujdate',
  'Ain Cheggag',
  'El Menzel',
  'Ait Seghrouchen',
  'Mrirt',
  'El Hajeb',
  'Ifrane',
  'Azrou',
  'Ain Leuh',
  'Ben Smim',
  'Dayet Ifrah',
  'Timahdite',
  'Almis Guigou',
  'Boufakrane',
  'Oulmès',
  'Khénifra',
  'Midelt',
  'Zaida',
  'Moulay Ali Cherif',
  'Itzer',
  'Aoufous',
  'Er-Rich',
  'Jorf',
  'Erfoud',
  'Rissani',
  'Merzouga',
  'Alnif',
  'Tinjdad',
  'Goulmima',
  'Tinejdad',
  'Ouarzazate',
  'Taznakht',
  'Agdz',
  'Zagora',
  'M\'Hamid El Ghizlane',
  'Tagounite',
  'Foum Zguid',
  'Tamegroute',
  'Tinghir',
  'Kelaat M\'Gouna',
  'Boumalne Dades',
  'Msemrir',
  'Imlil',
  'Asni',
  'Ouirgane',
  'Amizmiz',
  'Lalla Takerkoust',
  'Tahanaout',
  'Sidi Abdallah Ghiat',
  'Tameslohte',
  'Ait Ourir',
  'Essaouira',
  'Tamanar',
  'Smimou',
  'Haha',
  'Chichaoua',
  'Imintanoute',
  'Imi n\'Tanout',
  'Lqliaa',
  'Sidi Rahhal Chataï',
  'Sebt Gzoula',
  'Mzoudia',
  'Skoura',
  'El Kelaâ des Sraghna',
  'Bouabout',
  'Sidi Rahhal',
  'Ben Guerir',
  'Rehamna',
  'Youssoufia',
  'Chemaia',
  'Khouribga',
  'Oued Zem',
  'Boujniba',
  'Hattane',
  'Bejaâd',
  'Beni Mellal',
  'Kasba Tadla',
  'Fkih Ben Salah',
  'Souk Sebt Ouled Nemma',
  'Dir El Ksiba',
  'Bzou',
  'Zaouiat Cheikh',
  'Oulad Ayad',
  'Agadir',
  'Inezgane',
  'Ait Melloul',
  'Dcheira El Jihadia',
  'Drarga',
  'Temsia',
  'Aourir',
  'Tamraght',
  'Taghazout',
  'Imsouane',
  'Tamri',
  'Taroudant',
  'Oulad Teima',
  'Irherm',
  'Igherm',
  'Taliouine',
  'Aït Baha',
  'Biougra',
  'Massa',
  'Sidi Bibi',
  'Tiznit',
  'Sidi Ifni',
  'Mirleft',
  'Tan-Tan',
  'Tarfaya',
  'Akhfennir',
  'Laâyoune',
  'Boujdour',
  'Dakhla',
  'Aousserd',
  'Guelmim',
  'Assa',
  'Zag',
  'Fam El Hisn',
  'Akka',
  'Tata',
  'Foum El Hisn',
  'Tissint',
  'Allougoum',
  'Taghjijt',
  'Bouizakarne',
  'Bou Izakarn',
  'Ifni',
  'Lakhsas',
  'Sbouya',
  'Tafraout',
  'Anezi',
  'Ait Abdellah',
  'Tanalt',
  'Tioughza',
  'Arbaa Sahel',
  'Tleta Tagmoute',
  'Ameln',
  'Oujda',
  'Berkane',
  'Taourirt',
  'Jerada',
  'Ain Bni Mathar',
  'Touissit',
  'Ahfir',
  'Bouarfa',
  'Figuig',
  'Debdou',
  'Naima',
  'El Aioun Sidi Mellouk',
  'Guenfouda',
  'Martimprey du Kiss',
  'Ras El Ma',
  'Mechraa Hammadi',
  'Boudinar',
  'Saidia',
  'Zegzel',
  'Ben Taïeb',
  'Madagh',
  'Aklim',
  'Berriane',
  'Bni Drar',
  'Bni Khaled',
  'Bni Tadjite',
  'Saidia'
].sort();

export const getVilleNaissanceOptions = (inputValue = '') => {
  if (!inputValue || inputValue.length < 2) {
    return villesMarocNaissance.slice(0, 20); // Afficher les 20 premières par défaut
  }
  
  const normalizedInput = inputValue.toLowerCase().trim();
  
  return villesMarocNaissance.filter(ville =>
    ville.toLowerCase().includes(normalizedInput)
  ).slice(0, 50); // Limiter à 50 résultats
};
